### ISSUE TITLE
Test-PSFFunctionInterrupt doesn't catch Stop-PSFFunction

### ISSUE THREAD

**Issue by Splaxi** [PowershellFrameworkCollective/psframework#173]
I have a public function where I call some validation logic in a inner (non-public) function.

The inner function is like this:
```
function Test-Runtime {
    Write-PSFMessage -Level Verbose -Message "Testing if run on LocalHostedTier1 and console isn't elevated"
    if ($Script:EnvironmentType -eq [EnvironmentType]::LocalHostedTier1 -and !$script:IsAdminRuntime) {
        Write-PSFMessage -Level Host -Message "It seems that you ran this cmdlet <c=`"red`">non-elevated</c> and on a <c=`"red`">local VM / local vhd</c>. Being on a local VM / local VHD requires you to run this cmdlet from an elevated console. Please exit the current console and start a new with `"Run As Administrator`""
        Stop-PSFFunction -Message "Stopping because of missing parameters"        

    }
    elseif (!$script:IsAdminRuntime -and $Script:UserIsAdmin -and $Script:EnvironmentType -ne [EnvironmentType]::LocalHostedTier1) {
        Write-PSFMessage -Level Host -Message "It seems that you ran this cmdlet <c=`"red`">non-elevated</c> and as an <c=`"red`">administrator</c>. You should either logon as a non-admin user account on this machine or run this cmdlet from an elevated console. Please exit the current console and start a new with `"Run As Administrator`" or simply logon as another user"
        Stop-PSFFunction -Message "Stopping because of missing parameters"        

    }

}
```

In my outer function it looks like this:
```
Test-Runtime

 if (Test-PSFFunctionInterrupt) { return }
```

But that doesn't work.

Am I totally of what the point with Test-PSFFunctionInterrupt is in combination with         Stop-PSFFunction?

**Comment by FriedrichWeinmann** [comment]
Heya,

not really but also yes, you are off (a bit) on how it acts.
Thing is: `Test-PSFFunctionInterrupt` will only catch interrupts written by a `Stop-PSFFunction` called from within the _same_ command. Otherwise it wouldn't be able to distinguish between an inner command that should kill the outer command and a standalone command your function called that just happens to also use `Stop-PSFFunction`.

So what you do instead - which also happens to be in keeping of verb usage - is to have `Test-Runtime` return either $true or $false and test for that in your calling command.

One note on color coding:
```
<c=`"red`">
```
You are hardcoding colors. This works well enough until somebody changes console background color to red. The recommended way is to use `em` (emphasis) or `sub` (subtle), both of which can be changed by using the configuration system.
If changed color schemes are not an issue for you, explicitly picking a color of your choice is of course totally viable (but don't force a change on the colors represented by emphasis and subtle on the user - it's supposed to be his choice).

**Comment by FriedrichWeinmann** [comment]
Note 2) on the color tags:
You can totally use single-quotes for the tags for greater convenience:
```
<c=`"red`">
```
could become
```
<c='red'>
```
