### ISSUE TITLE
GELF Logging Provider

### ISSUE THREAD

**Issue by awickham10** [PowershellFrameworkCollective/psframework#225]
I put together a GELF logging provider that uses the PSGELF PowerShell module. Is this something you would be interested in including? If so I can submit a PR for it.

**Comment by FriedrichWeinmann** [comment]
Hi Andrew,

that sounds like it would be quite useful, so by all means, PR it, will be happy to have it.
I'll have to flag it as an 'Experimental' feature (or something like that), simply because I don't have any test systems and too little background with Graylog-style logging systems to give it my "No Breaking Changes" guarantee.

Cheers,
Fred

**Comment by FriedrichWeinmann** [comment]
Released in 0.10.29.160
Thanks again for the awesome contribution :)
