### ISSUE TITLE
Cross platform?

### ISSUE THREAD

**Issue by Stephanevg** [PowershellFrameworkCollective/psframework#258]
Hi Fred, whats up?

for PSHTML, I would like to add logging and configuration support. PSFramework sounds like a good candidate to consider. I do have these questions first:

1) this module Cross platform? (I coudln't find that info on the documentation website. 
2) Where are the configuration stored on linux (Could only find this -> https://psframework.org/documentation/documents/psframework/configuration/persistence-location.html )

**Comment by FriedrichWeinmann** [comment]
Heya @Stephanevg ,

keepin' busy, keepin' busy with lots of fun stuff. Totally in nerd wonderland right now ^^
That being said, glad you are considering the PSFramework for all your configuration and logging needs :)

1. It totally is cross-plattform. Admittedly, that statement is not quite that well place - it's in my [reliability promise statement](https://github.com/PowershellFrameworkCollective/psframework/blob/development/PSFramework/The%20PSFramework%20Reliability%20Promise.md)
2. The configuration files on linux are stored as json files in their respective folders. Of course, the registry locations are unavailable on linux and thus only the lower three locations are considered. For example the linux equivalent to %localappdata% can be found in `$Env:XDG_CONFIG_HOME/PowerShell/PSFramework/` (if XDG is available) or its fallback `$HOME/.config/PowerShell/PSFramework/` (courtesy of Joel Bennet's configuration module, since I don't really do much with Linux myself).

Regarding XPlat support, just to clarify some things:
I totally support running PSFramework on Linux or MAC. However I don't _do_ much on these platforms. What this means is I might not catch all bugs, but I sure as hell will try my best to swiftly resolve them when reported.

Cheers,
Fred

> PS: Bug Reporting

For reporting bugs there is a command in PSFramework that really helps with understanding what went wrong: `New-PSFSupportPackage` . If you have any issues that seem really weird, please use this and send the resulting zip for troubleshooting. You can also use this to ask _your_ users for debugging packages.

The file it generates inside the zip file is a compressed clixml file and can be read by Import-PSFClixml to get an object with ... comprehensive troubleshooting info.
