### ISSUE TITLE
filesystem logging provider - column headers?

### ISSUE THREAD

**Issue by alevyinroc** [PowershellFrameworkCollective/psframework#260]
When using the `filesystem` logging provider, I noticed that the logfile does not have column headers. The `logfile` provider does include headers.

Should column headings be added for `filesystem` or is this by design?

**Comment by FriedrichWeinmann** [comment]
Heya, this is actually more "by contract" than "by design"
The original format was a crapshot where I didn't think things through before releasing it. Adding headers now however would break any current automated log parser that are currently forced to explicitly specify headers. So going back and fixing it now would be a breaking change and I don't do those.

So what _will_ come this winter break is a configuration option to enable the "modern" file system log with additional columns and a header.

**Comment by FriedrichWeinmann** [comment]
Implemented in `0.10.31.176`
