### ISSUE TITLE
Powershell Core support

### ISSUE THREAD

**Issue by egor-yudkin** [PowershellFrameworkCollective/psframework#415]
Hey, I'm using this module for logging in my backup scripts. Currently those scripts are running on Windows machines, but I'd really like to use them on Linux.
Do you plan to add PowerShell Core support?

**Comment by FriedrichWeinmann** [comment]
Using it in PS Core is already fully supported.
Using it on Core myself daily ... but on Windows, If there is anything preventing its use on Linux, please tell me - definitely supposed to run there!

**Comment by dtrue** [comment]
I feel like this is probably an annoying question but I fee like since powershell 7 that maybe the error messages being reported using PSFramework are less direct than they use to be?  I've recently moved to using ps 7 core and vscode on windows, so maybe I'm going down the wrong path but I find myself needing to use Get-Error now.  Final question - about to use the configuration module but just curious if this is still the route to go with ps7.  Thanks!

**Comment by FriedrichWeinmann** [comment]
> I feel like this is probably an annoying question but I fee like since powershell 7 that maybe the error messages being reported using PSFramework are less direct than they use to be?

I don't think so - nothing changed in that regard.
But on PS7, the default display and other reporting tools are better, so I can see how the perceived advantage may change.
If you have found any concrete discrepancy between PSFramework on WinPS vs. PSCore, please show them - ideally with a minimal code reproduce - because I sure as hell try to make the user experience as balanced as possible!

> Final question - about to use the configuration module but just curious if this is still the route to go with ps7.

It absolutely is! It is designed to give the user as free a choice on how to provide configuration as possible, without you as the implementing developer having to care about that.
The value of this increases, the more diverse the potential audience, increasing its value as you move to Cross platform support.
As stated in my previous answer, PSFramework is supported on all Platforms that support PowerShell Core, so if you find any issues on any platform, please report them and I will try to fix the issue.

**Comment by dtrue** [comment]
The common scenario is I'm seeing the following error: 
 if (-not $Cmdlet) { throw $records[0] }
It then throws with the PSFramework line number as opposed to the cmdlet script line number.

**Comment by FriedrichWeinmann** [comment]
Aye, one of the limitations of the system, that I cannot change without introducing a breaking change (which I won't).
You can call `Stop-PSFFunction` with the `-Cmdlet $PSCmdlet` parameter to change the error signature.
You should find the full Script Callstack both in the error record and the message anyway (You can use `Get-PSFMessage` to retrieve the messages, including the errorrecord)
