### ISSUE TITLE
Single config file per module

### ISSUE THREAD

**Issue by blindzero** [PowershellFrameworkCollective/psframework#417]
Coming from old Unix I really prefer text-based config files that can easily be edited by users, especially for users preferences, etc.

Somehow it seems that PSF is not really supporting that by design?
Yes, I can register to different scopes, but PSF is generating one `psf_config.json` file in a directory `WindowsPowerShell\PSFramework\Config`. That results in all settings of all PSF-using modules in one file, which I would not assume as being 'handy'.

Using Export-PSFConfig / Import-PSFConfig is somehow unhandy as well...especially as it doesn't persist "description"...

I would prefer to use all functions of PSF but with having my own `ModuleName` Directory in the different scope spaces.

**Comment by FriedrichWeinmann** [comment]
Heya @blindzero , thanks for the Feedback!
Let's see …

> Somehow it seems that PSF is not really supporting that by design?

It was designed to be configured by the user through the cmdlets & functions dealing with configuration. I can see how supporting multiple files for auto-Import would be beneficial though and I suppose adding support for that would not be terribly hard.
I'll add that to the list, but the main file will win in case of conflict and will need to see how to best have it supported by Register-/Unregister-PSFConfig.

> Using Export-PSFConfig / Import-PSFConfig is somehow unhandy as well...especially as it doesn't persist "description"...

The description field of a setting is assumed to be set during initialization (kind of its manifest declaration), which is an explicit `Set-PSFConfig` call during module import. Due to that, loading anything other than the values themselves was never implemented.

The commands were primarily designed with CI/CD processes in mind and not really for interactive human use.

> I would prefer to use all functions of PSF but with having my own ModuleName Directory in the different scope spaces.

I'll see about how to best do that. One of the issues with that is potential conflict with the ModuleCache scenario (which is an entirely different use-case, if you plan on looking it up).
I _suspect_ it will end up working like this:

```powershell
# Register to default file
Register-PSFConfig -FullName MyModule.Setting1 -Scope FileUserShared

# Register to specific named file
Register-PSFConfig -FullName MyModule.Setting1 -Scope FileUserShared -Container MyModule
```

Will need to give that a few tests and thoughts. But would that meet your desired format?

**Comment by blindzero** [comment]
Hi @FriedrichWeinmann 

thanks for that instance react!

> > Somehow it seems that PSF is not really supporting that by design?
> It was designed to be configured by the user through the cmdlets & functions dealing with configuration. I can see how supporting multiple files for auto-Import would be beneficial though and I suppose adding support for that would not be terribly hard.
> I'll add that to the list, but the main file will win in case of conflict and will need to see how to best have it supported by Register-/Unregister-PSFConfig.

I really like that multi-layer-auto-import idea as it really gives a lot of flexibility.
However, it seems that the downside is that it seems to me as user interaction is only to be done over the software, not the config files?

> The description field of a setting is assumed to be set during initialization (kind of its manifest declaration), which is an explicit `Set-PSFConfig` call during module import. Due to that, loading anything other than the values themselves was never implemented.

Hm, maybe I that is coming more from that idea of users having a description in the config file to have a guidance when editing the file directly.

My 'implementation idea' was something like
* having a sample config file and putting it into one of the locations (e.g. LocalAppData) if not existing
* importing that file while initializing my module

> > I would prefer to use all functions of PSF but with having my own ModuleName Directory in the different scope spaces.
> I'll see about how to best do that. One of the issues with that is potential conflict with the ModuleCache scenario (which is an entirely different use-case, if you plan on looking it up).
> I _suspect_ it will end up working like this:
> 
> ```powershell
> # Register to default file
> Register-PSFConfig -FullName MyModule.Setting1 -Scope FileUserShared
> 
> # Register to specific named file
> Register-PSFConfig -FullName MyModule.Setting1 -Scope FileUserShared -Container MyModule
> ```

Yeah, or maybe I should work more with Export- & Import if it would support "description" field, rather than register?

Best,
M.

**Comment by FriedrichWeinmann** [comment]
> I really like that multi-layer-auto-import idea as it really gives a lot of flexibility.
However, it seems that the downside is that it seems to me as user interaction is only to be done over the software, not the config files?

If not "only", it certainly was the primary tool in mind.
As mentioned, I don't mind extending that, making file interaction more natural seeming. Also planning on iterating on the json format for json-based config data serialization, to give options that seem more humanly friendly.

> Hm, maybe I that is coming more from that idea of users having a description in the config file to have a guidance when editing the file directly.

You can have a description in the config file, it will just be ignored

> My 'implementation idea' was something like
> * having a sample config file and putting it into one of the locations (e.g. LocalAppData) if not existing
> * importing that file while initializing my module

While possible, this is actually not desirable, as you would be conflicting with other ways to define configuration (e.g. if the user registered a setting to registry). This has been a major headache when designing the configuration system - having the different locations cooperate in harmony, especially when for example the automatic import from registry may be performed well before your module is loaded (the auto-imported configuration happens on PSFramework import, not your module's import, as I have no way to differentiate between a module's config settings from a standalone setting, from a hybrid setting).

A problem with Json here is that I don't think there is a way to comment lines.
I may need to support PowerShell Document files as input (which would be pretty cool actually).
Every setting you would provide in that config file you explicitly import during module import would overwrite any otherwise persisted setting (in the current implementation anyway). So if you give a user a sample config file, that would be the new definitive configuration and override the entire rest of the system.

The idea is for your module to define the way a configuration setting behaves during import like this:

https://github.com/PowershellFrameworkCollective/psframework/blob/development/PSFramework/internal/configurations/path.ps1

And the rest would be handled by the system, _**with your module not needing to care about the details**_ (such as config files).
It was never supposed to be the module's role to tell the user how to define config ...

**Comment by blindzero** [comment]
Yeah, you are completely right...I might have been leaded more by the wish to have module that may support this config file stuff while it has also those other cool features of PSF which I would appreciate so much ;)
Feel free to close it if you think that it is not matching PSF's positioning.

**Comment by blindzero** [comment]
But having not all modules saved in one file would be something I would recommend anyway ;)

**Comment by FriedrichWeinmann** [comment]
> Yeah, you are completely right...I might have been leaded more by the wish to have module that may support this config file stuff [...]

Short of importing the description, you _can_ use it like you described!
You'll need to implement the path handling and automatic import yourself (Note: `Get-PSFPath` might help with that). It will not behave like the config system usually does - which is what I was trying to point out - but it will work.
You can combine that with an initialize call to make the description be part of in-memory config as well.

Basically, you'd explicitly call Import-PSFConfig during module import. I really need to update my docs on the extensibility of Import-PSFConfig, but basically, you can either use the default notation you get when you run Export-PSFConfig (which allows you to add fake description entries), or you could use the MetaJson configuration schema:

```powershell
Import-PSFConfig -Schema MetaJson -Path .\file.json
```

Which is ...
- Easier to read for the human
- Missing said documentation (sorry)

If you want to build an example configuration for the default mode:

- Define the settings using `Set-PSFConfig`
- For a more json export (without powershell serialization for complex powershell types) use the `-SimpleExport` parameter
- Use `Export-PSFConfig` to write the file

> The Downside

The only real downside to this process is that users that are used to PSFramework config will be confused when their Register-PSFConfig calls have no effect.

> ------------------------------------------

> But having not all modules saved in one file would be something I would recommend anyway ;)

Definitely on the list - as described in the previous post - for the next update on the configuration system (probably the update after the next major update I'm currently working on).

> Feel free to close it if you think that it is not matching PSF's positioning.

That's up to you - if you have any follow up questions on my first comment in this post, by all means, happy to keep the conversation up :)
I _will_ create a new dedicated issue for the feature of supporting multiple automatic import files, as well as psd1 files in addition to json and cross-reference it.

**Comment by FriedrichWeinmann** [comment]
Alright, see the two referenced issues for the feature update :)

Btw., one more thing:
If you want to use the configuration system in a non-standard way (which is perfectly fine with me), it might be beneficial to run the initialization with the `-Hidden` parameter, to hide them from random discovery of the user.
That way, users would be less inclined to use the default configuration commands on them.
