### ISSUE TITLE
How to avoid logging to multiple files?

### ISSUE THREAD

**Issue by DGOIT-Jan** [PowershellFrameworkCollective/psframework#479]
Hi!

Just tried your framework and it looks good for my logging requirements.

However, one thing bugs me and I think it's by design because of the separate runspace, but I need to understand it a bit further and configure it correctly.

I have some scripts open in my ISE and in each of them, I configure my provider like so:

`$paramSetPSFLoggingProvider = @{
		Name		 = 'logfile'
		InstanceName = 'MIM-UserActivation'
		FilePath	 = $LogDirectory + '\%Date%-MIM-UserActivation.csv'
		Headers	     = 'Timestamp', 'Level', 'Message'
		Enabled	     = $true
		CsvDelimiter = ';'
		TimeFormat   = 'yyyy-MM-dd HH:mm:ss'
	}
	Set-PSFLoggingProvider @paramSetPSFLoggingProvider`

In the next script, the InstanceName and the Path look like this:

`$paramSetPSFLoggingProvider = @{
		Name		 = 'logfile'
		InstanceName = 'MIM-GroupMgmt'
		FilePath	 = $LogDirectory + '\%Date%-MIM-GroupMgmt.csv'
		Headers	     = 'Timestamp', 'Level', 'Message'
		Enabled	     = $true
		CsvDelimiter = ';'
		TimeFormat   = 'yyyy-MM-dd HH:mm:ss'
	}
	Set-PSFLoggingProvider @paramSetPSFLoggingProvider`

After after firing both scripts, the messages are written to BOTH log-files, which is, u guess it, very annoying.

So, I want to be able to configure the provider at "script"-level and make sure, the messages from the scripts flies to the correct file specified in the provider.

I tried with

- Add-PSFLoggingProviderRunspace
- Remove-PSFLoggingProviderRunspace

but have not have success with it.

Please tell me how to make sure the messages of a script are written to the logfile specified in the script :)

Thanks!

**Comment by FriedrichWeinmann** [comment]
Heya, what you want to do is explicitly disable the logging provider once the script is done (and explicitly flush scripts).
So you'd place this at the end of the first script:

```powershell
Wait-PSFMessage # Wait until all logs are written
Set-PSFLoggingProvider -Name logfile -InstanceName 'MIM-UserActivation' -Enabled $false
```

**Comment by DGOIT-Jan** [comment]
Ok, thanks for your fast reply, I will try this!

But what does the parameter "InstanceName" mean? I thought it would be possible to write a message to a specific instance, but the Write-PSFMessage does not have this parameter...

**Comment by FriedrichWeinmann** [comment]
The `InstanceName` means you actually get multiple instances for the same provider. Previously that would have been a single logfile only.
Imagine you have two scripts:

```
script1 starts and logs to C:\logs\log1.csv
Then script1 calls script2
script2 starts and changes the logpath to C:\logs\log2.csv _thereby stopping all logging to log1.csv_
script2 finishes and script1 resumes
all further logging of script1 still goes to log2.csv
```

That was the previous state.

> but the Write-PSFMessage does not have this parameter...

That is a very, very intentional design decision.
You see, as far as PSFramework is concerned, your script code does not own the logging, but the one controlling the environment your code runs in.
All the message generating commands such as `Write-PSFMessage` will ever only send the message into the logging queue and provide hints, by which individual provider instances decide, whether they process the message or not.

This was built with modularity and toolbuilding in mind.
Lets say you write a script and each Write-PSFMessage targets the specific logging instance you want.
Now what if your coworker wants to use your script in her workflow, where she wants all logs of all changes to go into her Splunk server, rather than whatever logging you had provided?
Well, to do that she would now have to modify your script to allow for that (and keep doing that if you update your version or give up on any updates/bugfixes).

With this setup however, we can now provide code that integrates into the target logging, without having to know what they want to do for that. For example, a module could liberally include logging, without requiring a specific logging setup or requiring a custom logging config (and code) just for that module.
Lets use the [Active Directory Management Framework](https://admf.one) for example. It potentially executes massive, security relevant changes over entire enterprise networks, so you would want that logged.
Well, with this system users have the absolute liberty in how to consume this logging data, whether they want local csv files, Splunk, Graylog Azure Log Analytics or any other number of target systems (or any combination of them).

**Comment by DGOIT-Jan** [comment]
Thanks for that explanation!

But in your example you say that script2 changes the logpath to another file. In my short tests, script2 writes to the new file AND the one configured in script1. So both providers, the one configured in script1 and the one configured in script2, seem to be used.
But as I said, I haven't done any extensive testing yet.
Your previous hint with the deactivation of the provider works as expected :)

So, what is the best approach to provide a logging runspace so I don't have to do it in my scripts?
Is there any 'How-to' that I haven't found yet? I'm not a PS-Guru, so apologize my noob-questions :)

**Comment by FriedrichWeinmann** [comment]
> But in your example you say that script2 changes the logpath to another file. In my short tests, script2 writes to the new file AND the one configured in script1.

What I described was the state _before_ I introduced instances.
So ... the problem I solved with those `-InstanceName` parameters :) (and one of the most massive updates / rewrites behind the scenes ...)

> So, what is the best approach to provide a logging runspace so I don't have to do it in my scripts?

Actually, it's perfectly fine to include it into your scripts!
So long as you remember to disable it when you are done that's cool.
The `... your script code does not own the logging, but the one controlling the environment your code runs in` line was in regards to the thought behind the design decision into why the architecture is the way it is. That doesn't make it bad to put your logging config in your script - that coworker in the previous narrative could accept that config, it might fail in the background if the config doesn't work in her environment (which wouldn't hurt, really, just some red stuff happening where nobody sees it).

That said, what really happens with the logging thing is ... all `Set-PSFLoggingProvider` does is provide you with hints on how to use it (tab completion, which settings are available for a given provider). It doesn't actually create a logging provider instance at all!
What it does is set [Configuration Settings](https://psframework.org/documentation/documents/psframework/configuration.html) for the current session. These settings are then picked up by the background runspace that implements the logging and turned into logging provider instances.
So if you want to keep the logging outside of your script code and controlled by the environment, you can pick one of the many other ways to provide just these configuration settings.

### Setting up the logging config

> 1) Figuring out which setting and which value

The easiest way to figure out the settings - probably better than reading the docs - is to just define them interactively with `Set-PSFLoggingProvider` and then use `Get-PSFConfig` to figure out the settings needed:

```powershell
Get-PSFConfig '*.MIM-UserActivation.*' | ft FullName, Value -AutoSize
```

> 2) Providing the configuration

Depending on how you want to log, having machine-global settings is fine, in which case you could just write the settings into registry under HKLM:

```powershell
Get-PSFConfig '*.MIM-UserActivation.*' | Register-PSFConfig -Scope SystemDefault
```

When registered that way, they will be picked up automatically on [every single powershell console session](https://psframework.org/documentation/documents/psframework/configuration/persistence-basics.html) that imports PSFramework.
Generally speaking, this isn't all that useful in most cases.
You already have the filesystem provider offering a global debuglog for just-in-case situations and otherwise it's just not as flexible.

For traditional script approaches, if you want to keep the logging config (and other config) out of the scriptfile itself, what you can do is have it look for a config file in the same folder as the script.
For that you need to import those config files. Some related docs for more details if interested:

+ [Import-PSFConfig](https://psframework.org/documentation/documents/psframework/configuration/persistence-manual-export-import.html)
+ [The MetaJson configuration Schema](https://psframework.org/documentation/documents/psframework/configuration/schema-metajson.html) (check here for the config file layout documentation, lots of examples)

But simply put, you could put this in the beginning of your script:

```powershell
if (Test-Path "$PSScriptRoot\config.json") {
    Import-PSFConfig -Schema MetaJson -Path "$PSScriptRoot\config.json"
}
```

> That other, fundamentally different option

What I do for most of my work nowadays instead is this:
Almost all of my business code is stored in modules. The scripts are very little more than wrappers around the modules.
That way, there is no way the script could be used for anything else (because what you really want to reuse is in the module), so I don't need to care about hardcoding some logging into my scriptcode.
Then I just enable the provider, run the module, disable the provider.

Of course that's not actually viable in every situation, as it requires being able to conveniently use modules (for example, it's often an issue in orchestration tools, that give you only the ability to specify one file in total).

**Comment by DGOIT-Jan** [comment]
Thanks again for your detailed explanation!
Maybe I'll dig deeper into this stuff if I need to :-)
Have a nice day!
