### ISSUE TITLE
Register-PSFConfig  not saving the Description of the Configuration (not persisted) in case of scope FileSystem

### ISSUE THREAD

**Issue by Stilmant** [PowershellFrameworkCollective/psframework#510]
PowerShell 7

Register-PSFConfig  not saving the Description of the Configuration (not persisted) in case of scope FileSystem

**reproduce** 
```
Set-PSFConfig -Module MyModule -Name General.Test -Value "Test Value" -Initialize -Validation string -Description "This is a Description"
Register-PSFConfig -Module MyModule -Scope FileSystem
```
Open new powershell session 
`Get-PSFConfig -Module MyModule`
**Result**
Description field is empty
**Expected** 
Description should be the value set

**Note**
Write-PsfConfigFile / Read-PsfConfigFile seems to not handle the 'Configuration' description field.

**Comment by FriedrichWeinmann** [comment]
That is correct and by design.
Aside from the actual values, all metadata for configuration is expected to be applied during initialization (including description, validation, handler, export config, hidden state, ...).
The scope written to in this regard is of no consequence - exporting to file will also not include the description.

**Comment by Stilmant** [comment]
Ha then I'm a bit confuse. 
First by the -Initialize option. "When initializing a configuration, it will only do a thing if the configuration hasn’t already been initialized"  but it will set the Description even if the Settings has a Value already set. So there is action even with Initialize option.

If I set Settings in myModule then restart a shell session and interrogate Get-PSFConfig (MyModule is Not initialized), I can see MyModule configs but no Description. I'm not getting why I would not see the Description at that moment. I don't plan at that step to initialize myModule (usage of the module will be done at later time) but I want to update it's configuration. (since to do so I use PFSFramework only there is no initialization on myModule side right?) 

I'm maybe did not understood what is a Module initialization.

**Comment by FriedrichWeinmann** [comment]
Alright, let's see.
When the configuration system talks about initialization, it literally only means only `Set-PSFConfig` calls that include the `-Initialize` parameter.
Example:

```powershell
Set-PSFConfig -FullName MyModule.Test.Setting1 -Initialize -Description "Example 1"
Set-PSFConfig -FullName MyModule.Test.Setting1 -Initialize -Description "Example 2"
Get-PSFConfig -FullName MyModule.Test.Setting1
# Example 1
```

Run this in a console, and you will see, that the second description was not applied.
The assumption is, that during your module's import you initialize your settings, which declares how they behave, what data types they expect, what their _default values_ are and a nice description so users understand what it is about.
If a value already exists before initialization - for example if you used `Register-PSFConfig` to persist it - that value will take precedence over the value provided during initialization.
Example:

```powershell
Set-PSFConfig -FullName MyModule.Test.Setting2 -Value 23
Set-PSFConfig -FullName MyModule.Test.Setting2 -Value 42 -Initialize
Get-PSFConfig -FullName MyModule.Test.Setting2
# 23
```

One thing it makes sure happens during initialization is test, whether previously provided values meet the validation rules (because technically, you can totally persist invalid values, if you set config before loading your module).
Example:

```powershell
Set-PSFConfig -FullName MyModule.Test.Setting3 -Value 'Foo'
Set-PSFConfig -FullName MyModule.Test.Setting3 -Value 42 -Initialize -Validation integer
# Warning: "Foo" is not a valid integer
Get-PSFConfig -FullName MyModule.Test.Setting3
# 42
```

Concluding: [Initialization](https://psframework.org/documentation/documents/psframework/configuration/initialize.html) is the declaration, of how a setting behaves. The configuration of your configuration setting. You do it during module import, it respects previously configured values, so long as they are valid.

**Comment by Stilmant** [comment]
Thanks a lot for the long description. I finally understood the behavior of -Initialize (except I didn't see that the description is updated on initialization if the description is null, but it is not updated if the description is not null).

As for my original problem, I think you are assuming that a module would always be loaded when the user wants to inspect its parameters, right? (This works fine for PSFramework since the function to read the parameters is loading that module) However, let's say I connect to a server and want to inspect multiple parameters (maybe for multiple modules). At that point, the descriptions are not present and I would have to load a module (assuming I schedule the parameter setup correctly) to get the descriptions associated with that module. 

Also, why not have the description in the files (let's say I want to manually access the files to see the settings... there are no descriptions associated and so it's a little hard years later to figure out what each setting is, right?)

I'm more asking now more to be sure I understand the philosophy, I believe I may miss something.

**Comment by FriedrichWeinmann** [comment]
The decision to keep out the description was mostly made for three reasons:

+ Interacting with the settings outside of its parent module (if such exists) is rarely useful, so it was deemed an unlikely scenario
+ Simplicity. Name-Value pairs are easy to manage, adding a third (or more) elements would add complexity
+ Chronology. I just didn't think about adding that when I originally set up the architecture. After that, adding it would have taken non-trivial effort to implement consistently across all configuration scopes without a breaking change.

**Comment by Stilmant** [comment]
Thank you for the precisions. I will close the Issue now as it is reported as the current behavior is so by design.
I would like to point out that I have a doubt about the notion of 'unlikely scenario' since offering a Module that allows to list the parameters of all the modules for which it is used as a framework means that these utility functions are used outside the said modules. 
However I'm very new to Powershell and therefore it is more likely that I have a wrong approach of Powershell usage.. I will see with time. 
Thanks. 
So far I will do a workaround by creating a dedicated function inside my module to list its own settings.
