### ISSUE TITLE
Cannot write to Logfile while Filebeat is running

### ISSUE THREAD

**Issue by jakobzudrell** [PowershellFrameworkCollective/psframework#513]
I experienced an issue where Write-PSFMessage does not append to a file when being set up with the logfile provider while the Filebeat application is running in the background.

Here is my PSFLog setup on top of ExampleModule.psm1;
`
$paramSetPSSFLoggingProvider = @{
    Name = 'logfile'
    InstanceName = 'ExampleModule'
    FilePath = 'C:\IS\log\ExampleModule_%Date%.csv'
    LogRotatePath = 'C:\IS\log\ExampleModule_*.csv'
    Enabled = $true
}

Set-PSFLoggingProvider @paramSetPSSFLoggingProvider
`

This is the filebeat handle;
`
→ tools:\› .\handle.exe -a -u | findstr Example
  398: File  (RWD)   C:\IS\log\ExampleModule_2022-03-08.csv
`

I the behavior can be reproduced quite simply;
1. Stop-Service filebeat
2. WritePSFMessage in an endless loop
3. Check your log file -> messages are being appended
4. Start-Service filebeat
5. No more messages are being appended to the logfile
6. Stop-Service filebeat
7. Messages are being appended again

I think this has something to do on how PSFramework or PowerShell in general handles files.
Can someone help me with this case?

**Comment by FriedrichWeinmann** [comment]
Hi Jakob,
this is mostly due to the way it currently does not maintain a persistent filehandle - apparently, the filebeat service prevents reaquisition of said handle by locking it itself.

I have a pending feature-issue to change that (which would also improve logging throughput):
https://github.com/PowershellFrameworkCollective/psframework/issues/463

I'll prioritize it for the next release (which is overdue, but RL keeps messing with me). If you watch that issue you'll get notified once the fix is in. I'll attempt to make it soon(tm), but I cannot commit to a specific date for now, sorry :(

**Comment by jakobzudrell** [comment]
Hi Friedrich,
thanks for that quick response! 

I've put a watch on it and will gladly wait for an update on this :)

BR Jakob

**Comment by pierrediancourt** [comment]
I'm encountering the same kind of issue.  
Far less lines are written by PSFramework in the log file when filebeat is running.   
So, i can't use filebeat for until #463 is released.

@jakobzudrell, thank you for your work on this project so far !

**Comment by pierrediancourt** [comment]
The use the "filestream" input in the filebeat configuration instead of the "log" one and it seems to fix my issues   

@jakobzudrell this attribute seems stable since release 7.14 if you want to try too. I used v7.17 in my tests.   
https://www.elastic.co/guide/en/beats/filebeat/7.14/filebeat-input-filestream.html

**Comment by pierrediancourt** [comment]
Hello,
I'm seeing that a new version as been published on the PSGallery but can't find the release note online or even a release item on github. 
So, in doubt, i tested this issue again and I can tell that it's not fixed with version 1.7.226.

**Comment by FriedrichWeinmann** [comment]
Implemented in 2.7.235
Please verify, but other services should no longer be able to interfere through routine file access

**Comment by pierrediancourt** [comment]
Thanks a lot.
I'll probably test and report on next week !

**Comment by jakobzudrell** [comment]
Thanks for investigating! I will also try to test this the coming week :)

**Comment by pierrediancourt** [comment]
Alright, for me it works like a charm ! 

Tested with filebeat v7.17 and v8.2.0. 
It may be interesting to note I have "type: filestream" in the config.
I compared the number of items i get in Kibana compared to the number of lines in the logfile generated by PSFramework and it's perfect :)

Thank you very much @FriedrichWeinmann for your great work <3

**Comment by FriedrichWeinmann** [comment]
Found the issue with the duplicate headers, fixing it in the version shipping today

**Comment by FriedrichWeinmann** [comment]
Released/Resolved in 1.7.244
