### ISSUE TITLE
When checking for pgging Errors i get an Error :P

### ISSUE THREAD

**Issue by AaronG1234** [PowershellFrameworkCollective/psframework#538]
$LogFile = C:\Temp\MyLogFile.csv
#Log To File
$paramSetPSFLoggingProvider = @{
    Name         = 'logfile'
    InstanceName = 'MyLog_File'
    FilePath     = $LogFile
    Enabled      = $true
    Wait         = $true
}
Set-PSFLoggingProvider @paramSetPSFLoggingProvider
(Get-PSFLoggingProviderInstance -ProviderName logfile -Name MyLog_File).Errors

I get:

InvalidOperation: 
Line |
  58 |          $script:writer.Encoding = [PSFramework.Parameter.EncodingPara …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 'Encoding' is a ReadOnly property.

still true after i try to write some psfmessages

**Comment by FriedrichWeinmann** [comment]
Sorry about the late response, was off on vacation.

Provider instance errors will never go away and this one happens at the beginning when starting the provider instance.
It means in the current release it ignores the encoding setting - the next release (working on it since I'm back from vacation now) will fix that.
It's also the reason why it always only was one error and not many, as subsequent messages would not cause issues (at least not due to this).
