### ISSUE TITLE
Understanding Message Prefix Configurations

### ISSUE THREAD

**Issue by ev-dev** [PowershellFrameworkCollective/psframework#542]
Hey I've noticed that a few of the default configs for messages make use of some kind of templating and I was wondering how one might go about customizing these values. 

Examples can be found via `Get-PSFConfig -FullName PSFramework.Message.Style.Prefix*`

Some of the relevant default values are (left column is the FullName of the config property)
- `PSFramework.Message.Style.Prefix.Error` _defautls to_ `##vso[task.logissue type=error;]`
- `PSFramework.Message.Style.Prefix.Significant` _defaults to_ `##[section]`
- `PSFramework.Message.Style.Prefix.Verbose` _defaults to_ `##[debug]`
- `PSFramework.Message.Style.Prefix.Warning` _defaults to_ `##vso[task.logissue type=warning;]`

I couldn't find much about these template strings in the docs and after combing through some of the source code for messages, I still couldn't figure out how these values get transformed into their final strings so I figured I'd ask :P 

ps. thanks for all the great work on this project!

**Comment by FriedrichWeinmann** [comment]
Heya Evan,
thanks for pointing out this feature was broken!
As it was, only warning was being respected and the error part would only pick up on warnings with tag error, not with level error itself (which came later and I forgot to add it to the feature).

One of those extra feature requests I implemented but did not test sufficiently and never noticed because I don't use it myself.
Problem found and fixed, will be in the next release later today.

**Comment by FriedrichWeinmann** [comment]
Released/Resolved in 1.7.244
